-- PCM 数据库初始化脚本（已弃用）
-- 请使用 init-db.sh 代替。
-- 旧版 SQL 脚本无法正确处理多数据库创建，因为：
--   1. POSTGRES_DB (pcm_policies) 已由 entrypoint 自动创建，再 CREATE 会报错
--   2. \c 是 psql 元命令，在某些执行方式下不可用
-- 新的 init-db.sh 使用 shell 脚本调用 psql 分别连接不同数据库。
